import { catchErrors } from "../errors";

export const resetDb = catchErrors(async (req, res) => {});
